### ISSUE TITLE
Search stops working properly on large forums

### ISSUE THREAD

**Issue by marcozambi** [flarum/core#1042]
After having imported about 18000 discussions and 256000 posts from my existing SMF2 forum (I wrote a specific tool for that) I noticed that all the searches I was launching were generating several server Error 500. Flarum became unresponsive then for several minutes, despite many tries to simply refresh the home page.
Initially I started small import tests, taking in only few hundred then thousands of posts, and every was working very well.
When the number of imported posts goes above 60000 the search functionality starts to slow down considerably. At 100000 imported posts, every search using a single term reach a good end only after at least 10 to 20 seconds of waiting, while _99%_ search with 2 or more words fails with an Error 500.

I ran numerous tests trying to understand whether it could merely be a configuration issue on my server's side, but after having performed a flarum installation and a subsequent data import on a second sever (double the "power" of the first one, 8 GB of RAM, quad core, OS ubuntu 16.04, 60 gb ssd disk) and having run in the same exact problems, I am now convinced that there are some too-greedy or inefficient queries which are literally killing the server.

I have documented in detail my experiments here [on Flarum Community](https://discuss.flarum.org/d/3758-flarum-search-functionality-error-500/13)

An example of the query creating the problem is visible here [flarum_error_500.txt](https://dl.dropboxusercontent.com/u/25636589/flarum_error_500.txt)

I would be more than happy to help either doing more tests or receiving a few tips to understand the mechanisms and read the source code for the search functionality in Flarum.

**Comment by franzliedke** [comment]
Hello @marcozambi, thanks for putting so much work into this!

Judging from [your TXT file](https://dl.dropboxusercontent.com/u/25636589/flarum_error_500.txt), my first guess is that we first run a query that matches the text content against the search term, but **returns all results**.

Thus, the next query, which is supposed to, then has these ridiculously long WHERE and ORDER BY clauses. (Thus, performance probably varies greatly depending on the number of posts that match a particular query, not so much the overall number of posts in the database.)

This means we need to apply a limit (25?) to the query in the `MySQLFullTextDriver` class, which you can find [here](https://github.com/flarum/core/blob/2d5090ef12b27659213129f9e04d255501e49ff7/src/Core/Search/Discussion/Fulltext/MySqlFulltextDriver.php). All other files related to searching can be found in the [src/Core/Search folder](https://github.com/flarum/core/tree/2d5090ef12b27659213129f9e04d255501e49ff7/src/Core/Search).

@marcozambi Are you interested in trying to submit a fix for this?

**Comment by marcozambi** [comment]
Hi @franzliedke, I could give it a try but since I have zero experience with Flarum code, it might take some time. But I will try indeed!

**Comment by terabin** [comment]
Can I give a try?

**Comment by marcozambi** [comment]
Ok, I started to read the code and try to grasp the Laravel classes behind this functionality, and I kinda got a bit how it works. My way into knowing Laravel DB interface is still a long journey, but... good news.
Simply adding a limit of 100 returned discussions in the code like this;
`$discussionIds = Post::where('type', 'comment')
            ->whereRaw('MATCH (`content`) AGAINST (? IN BOOLEAN MODE)', [$string])
            ->orderByRaw('MATCH (`content`) AGAINST (?) DESC', [$string])
            ->limit(100)
            ->lists('discussion_id', 'id');`
has solved the problem and actually I can finally run any query receiving results in a matter of 3-4 seconds from the request start.

I pushed up the limit, as a test, to 1000 discussions and it still works even if the running time increases to at least 10 to 20 seconds.

I'd encorage you to add a configuration option for this in the Administrative interface fo flarum, to let the users tune it according to their servers capabilities, and with a default value low enough, possibly 25 as you suggested.

**Comment by franzliedke** [comment]
That's great to hear, thanks for looking into it!

I don't think we need to make this configurable - it all depends on how many search results we want to show. @tobscure does the interfaces, he should decide.

For the future we should probably keep in mind that we might want to add a "Load more" button - this would then result in also adding an OFFSET clause to the query.

**Comment by marcozambi** [comment]
Thanks Franz, actually you're perfectly right. The added OFFSET solution is perfect because hardcoding an arbitrary maxmimum number of results excludes a large number of results in large forums with hundreds of thousands of discussions.
A "buffered" solution, which returns a relatively large number of results with the first query, then followed by more OFFSET-ed queries if necessary could be considered. This way further queries (with OFFSET serr) are triggered only if the user has gone through the whole set of initial returned entries without finding what he/she was looking for.

**Comment by thorerik** [comment]
Adding support for eg. Elasticsearch as a search backend is perhaps a good idea. Though possible Fulltext search in mysql/postgres are less than ideal without large full-text indexes to speed up the process.

**Comment by WebNawi** [comment]
Thanks for finding this clue.

Now, There will not any "something get wrong..." message error anymore 👍 
My dedicated server still get quick search result within secon or two with value = 100.

But, I decide to use value 50 for 2M+ posts.. forum. And trying to switch between Relevance, Oldest, Newest, Top selection... and running smooth..

This is common problem facing the big forum owner.
I used this trick for my Old MyBB Forum..  afaik, many years ago someone from MyBB created as a plugin/extension which is hard-limit this query..

Then finally MyBB implement this function on their admin dashboard.
See this screenshot 😎 

![search](https://cloud.githubusercontent.com/assets/16497413/19804736/6d87c8fa-9d3a-11e6-93b5-a39fc9ce56d0.jpg)

**Comment by WebNawi** [comment]
Here they're.
As you can read.. Standard vs Full Text search available to choose.
![full](https://cloud.githubusercontent.com/assets/16497413/19804826/06880718-9d3b-11e6-8c59-fdaceb1dcd0d.jpg)

**Comment by fingonpalantir** [comment]
I think add elasticsearch is a good idea.

**Comment by tobscure** [comment]
I've made some progress on this, but have run into the same issue as https://github.com/flarum/core/pull/1334. So will need to sidetrack a bit to fix up the permission system.
