### ISSUE TITLE
Images in posts can throw off PostStream scroll

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#392]
I posted this on Gitter. I can't really express with words what's going on, other than to say that clicking on topics will not take me to the last comment in it, and that trying to go to the most recent comment takes clicking twice. Screen cap follows:

![Navigation bug](https://cloud.githubusercontent.com/assets/8352292/9592823/13558c82-5015-11e5-9ad5-b00dca915422.gif)

**Comment by tobscure** [comment]
I've noticed this at times too, but it's one of those ones that are difficult to reproduce consistently. We'll get to the bottom of it eventually though!

**Comment by franzliedke** [comment]
I often see a jump with the result of not seeing the first unread post when the discussion contains images (which seem to be loaded after jumping to the correct place in the discussion).

**Comment by tobscure** [comment]
@franzliedke That is indeed another issue (but I don't think it's the cause of the problems in the screencap above). How would we fix that, though? Maybe we could set an onload handler to anchor the scroll position when we render the posts?

**Comment by franzliedke** [comment]
Yep, sounds like the only solutio.

**Comment by franzliedke** [comment]
I just stumbled across this library, that should fix the image load scrolling behavior: https://github.com/changbenny/scrollbear

**Comment by askvortsov1** [comment]
Possible duplicate of https://github.com/flarum/core/issues/285?

**Comment by askvortsov1** [comment]
Fixed in #2160

**Comment by askvortsov1** [comment]
Actually, I'll reopen this for now as afaik we haven't tested the effects of the new changes on posts with images that load after the posts have loaded.

**Comment by matteocontrini** [comment]
This is related to #1678 as well.

Also: since this issue was created, Chrome and Firefox introduced scroll anchoring, which should have reduced this issue a lot.

**Comment by matteocontrini** [comment]
I'm posting here because I think this isn't actually related to images. I have a user reporting that this is still happening to him even in discussions where there are no recent images, and the behaviour he's seeing is exactly the one of the GIF in the first post (where I see no images, anyway).

I'm running beta.15 with commits d59a5922609c012d3cba2148e498d78737ed4b07 and 30c4c139eb15c1f9bf809b58be5a2d4c918cc6ae cherry-picked, which have to do with the PostStream. The user is using Chrome on Android/desktop. I haven't personally seen this issue recently, but apparently it's still there even after recent improvements.
