### ISSUE TITLE
Problems with utf-8 characters in emails

### ISSUE THREAD

**Issue by lcarlos-fokus** [flarum/core#537]
See example below:

```
Hey lcarlos!

rafaelazem mentioned you in a post in Transportadora no FKcarrier - dobrando o valor do frete.

http://www.modulosfk.com.br/modulosfk/flarum/d/19/6

---

@lcarlos resolvido! Muito obrigado!

Apenas uma &uacute;ltima d&uacute;vida, o FKcorreios G2 substitui o FKcarrier em suas funcionalidades, isto?

Obrigado!
```

**Comment by Luceos** [comment]
E-mails should be rewritten to be html and use a proper encoding, Mailer class automatically generates a text only variant if needed.

**Comment by dcsjapan** [comment]
Related to https://github.com/flarum/core/issues/241

**Comment by Averell7** [comment]
The reason is that the message is incoherent. Header indicates : Plain text / Utf8 and the content is converted in Html entities. In French, the result is unreadable. Here is a part of the source code of a message which informs of a new post : 

```
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
(...)
---
Le probl&egrave;me de la ligne t&eacute;l&eacute;phonique a &eacute;t&eacut=
e; r&eacute;par&eacute;,
--- 
```

The original text is : Le problème de la ligne téléphonique a été réparé
Le problème de la ligne téléphonique est réparé. 

For a quick solution, the best option would be to suppress the conversion of accentuated characters to html entities. From my tests, I conclude that this happens before the use of the blade file : 
\flarum\extensions\flarum-subscriptions\views\emails\newPost.blade.php 
I have translated this file to French, and I have to use Utf-8. It works fine. 

The problem is that the result of : 
`strip_tags($blueprint->post->contentHtml)`  
is already translated in Html. I tried :
`strip_tags($blueprint->post->content)`
The result is the same.

**Comment by Averell7** [comment]
I made some additional tests :  

Since the object contains the following properties : 
```
Object.assign(Post.prototype, {
  number: Model.attribute('number'),
  discussion: Model.hasOne('discussion'),

  time: Model.attribute('time', Model.transformDate),
  user: Model.hasOne('user'),
  contentType: Model.attribute('contentType'),
  content: Model.attribute('content'),
  contentHtml: Model.attribute('contentHtml'),
  contentPlain: computed('contentHtml', getPlainContent),

  editTime: Model.attribute('editTime', Model.transformDate),
  editUser: Model.hasOne('editUser'),
  isEdited: computed('editTime', editTime => !!editTime)
```
I modified the blade file to add : 

TEST

```
contentType {{ $blueprint->post->contentType }}
content {{ $blueprint->post->content }}
contentPlain {{ $blueprint->post->contentPlain }}
contentHtml {{ $blueprint->post->contentHtml }}
isEdited  {{ $blueprint->post->isEdited }}
```
The result in the email is : 

---
```
TEST

contentType 
content Le probl&egrave;me de la ligne t&eacute;l&eacute;phonique est r&eacute;par&eacute;
contentPlain 
contentHtml &lt;p&gt;Le probl&egrave;me de la ligne t&eacute;l&eacute;phonique est r&eacute;par&eacute;&lt;/p&gt;
isEdited  
```
Conclusion : "content" is already converted to html entities, and contentPlain is empty. 
So I don't know what to do.

**Comment by Luceos** [comment]
Haven't read through all of this, but can imagine the blade template uses double accolades instead of accolade and double exclamation marks. The difference is between allowing raw html (latter)...

**Comment by Averell7** [comment]
Here is the fix, not perfect, but indicating the direction. 

To turn the mime type in html instead of plain : 

in flarum\vendor\flarum\flarum-ext-subscriptions\src\Notification\NewPostBlueprint.php, line 63, change 'text' in 'html'. Or better, create a multipart email, with both versions : 

```
 public function getEmailView()
    {
        return ['html' => 'flarum-subscriptions::emails.newPostHtml',
                'text' => 'flarum-subscriptions::emails.newPost'];
    }
```

Then create a new blade file, newPostHtml.blade.php and suite it to your needs. 

I attach my blade files (from flarum\vendor\flarum\flarum-ext-subscriptions\views\emails) 
[NewPost-blade_files.zip](https://github.com/flarum/core/files/204208/NewPost-blade_files.zip)

It is not perfect because the end of paragraph marks are not converted to html code, and the text of the post is a solid block. Nevertheless, it is MUCH MORE readable. Here is the message received : 

---

Hello pierre

Averell a publié une réponse dans une discussion que vous suivez: test

Pour voir les nouvelles interventions, visitez le lien suivant:
test

---

Le problème de la ligne téléphonique a été réparé

---

Vous ne recevrez pas d'autres avertissements concernant cette discussion tant que vous n'aurez pas été lire les derniers messages.

---

WARNING : if you edit the blade file, write it in utf8, and be careful that the BOM must NOT be added in the beginning. I use Scite, and the encoding must be "UTF-8 cookie" and not "UTF-8"

**Comment by Averell7** [comment]
@Luceos thanks for your interest. Could it be possible to set a milestone for this issue ?

**Comment by franzliedke** [comment]
This will cause characters to be HTML escaped:

    contentHtml {{ $blueprint->post->contentHtml }}

Try this instead:

    contentHtml {!! $blueprint->post->contentHtml !!}

**Comment by Averell7** [comment]
Hello, @Luceos I didn't understand what you meant, but it was what Franz explained, and it is the solution. The bug is fixed. 

Now I don't know if developers will want only to fix it, or take in consideration now what you wrote above : "E-mails should be rewritten to be html and use a proper encoding". The code above gives a part of the answer, but there is still the problem of end of paragraph marks which are not converted to html codes. 

At this point, should I create a PR for the fix ?

**Comment by franzliedke** [comment]
Until we have time to implement flarum/issue-archive#426, a fix for this would be welcome, yes. :)

**Comment by Luceos** [comment]
@Averell7 btw. Kudos for researching this completely  ;)

**Comment by tobscure** [comment]
Probably not necessary/a good idea to use the unescaped output `{!! !!}` tags for everything, as it's a security issue (HTML injection). I think it should only be necessary around the contentHtml.

**Comment by Averell7** [comment]
@franzliedke  I have now a code which sends multipart messages, html and plain text, with clickable link in html. This solves flarum/issue-archive#426. I am using the code explained above : 

```
public function getEmailView()
    {
        return ['html' => 'flarum-subscriptions::emails.newPostHtml',
                'text' => 'flarum-subscriptions::emails.newPost'];
    }
```

and then two blade files. 

Here is the model I am working on, I show only the part which displays the message, there is no problem for the rest of the file. 

```
<br>
---<br>
<br>
{!! str_replace(chr(10), "<br>", htmlentities(strip_tags($blueprint->post->contentHtml))); !!} <br>
<br>
---<br>
<br>
```

I forked flarum-ext-subscriptions, because it is easier for you to see what I have done.
A translatable version will be ready today

**Comment by Averell7** [comment]
Hello, I think my job is finished. I implemented : 
- multipart email message  html/plain text
- correct formatting, either in html or in plain text. 
- translation of the message

What could be done : 
Adapt the html model to create something more beautiful. But I think this is not my job. 

I consider this bug (#537) an bug flarum/issue-archive#426 are fixed. 

Could you verify and push this to the beta-6, I would appreciate because it caused some hours of night work (you know what I mean :smile: )

**Comment by dcsjapan** [comment]
I can't check the code for you, but I can offer some suggestions regarding the language resources.

First, please take some time to read the [Internationalization docs](http://flarum.org/docs/extend/internationalize/), which explain the standard format to be used when adding translatable strings to Flarum. If you don't follow this format, you'll only be creating a new issue that someone else has to deal with before your code can be added to the project.

There is a specific format for email strings. Here's an example from [`core.yml`](https://github.com/flarum/flarum-ext-english/blob/master/locale/core.yml) in the English language pack:

```
    # These translations are used in emails sent when users change their email address.
    confirm_email:
      body: |
        Hey {username}!
        Someone (hopefully you!) has changed their email address on {forum} to this one.
        If this was you, simply click the following link and your email will be confirmed:
        {url}
        If this was not you, please ignore this email.
      subject: Confirm Your New Email Address
```

Each email should consist of two parts:

- The body, represented as a literal block, and
- The subject line

The key names for these two parts should be `body` and `subject`; they should be namespaced under a key name that distinguishes the email from other emails. So the namespacing for the resources that you added should look something like this:

- `flarum-subscriptions.forum.new_post_notification.body`
- `flarum-subscriptions.forum.new_post_notification.subject`

I'm not sure about the syntax you're using for the `app.translator.trans()` calls; @tobscure can tell you whether it can stand as is.

Once you've got your namespacing and translator calls straightened out, please consider forking the English language pack repo and adding the necessary phrases there. That extra effort will make it easier for the devs to review your code and add your changes in a timely fashion.

**Comment by franzliedke** [comment]
@Averell7 Where is your code? Did you send a PR?

**Comment by dcsjapan** [comment]
No PR, you can see it here:

https://github.com/flarum/flarum-ext-subscriptions/compare/master...Averell7:master

**Comment by Averell7** [comment]
@dcsjapan thanks for the comment. I thought quite a lot about it. The reason is : This file uses a very special format : .blade.php. 
I improved my code, because what I am proposing is now full blade format. Here it is : 
```
{!! app()->translator->trans('flarum-subscriptions.forum.email.hello') !!} {{ $user->username }}!

{{ $blueprint->post->user->username }} {!! app()->translator->trans('flarum-subscriptions.forum.email.new_post') !!} {!! $blueprint->post->discussion->title !!}

{!! app()->translator->trans('flarum-subscriptions.forum.email.check_link') !!}
{{ app()->url() }}/d/{{ $blueprint->post->discussion_id }}/{{ $blueprint->post->number }}

---

{!! strip_tags($blueprint->post->contentHtml) !!}

---

{!! app()->translator->trans('flarum-subscriptions.forum.email.no_more_notifications') !!}
```
It is just impossible to use the  specific format for email strings because there are no php variables here. So we have two options, and I cannot decide between them : 

* 1. Full blade format (above) and separate strings for each small block of text. The same strings will be used for the html and plain text formats
* 2. Rewrite the file in standard php format (no problem afaik), and then the  specific format for email strings can be used. There will be specific strings for the plain text and html format. 

At this point I cannot go further. The developers must first choose and tell me if they want to keep the blade.html format (above) or allow me to switch to standard php format. Then I can finish the job, following your indications.

**Comment by dcsjapan** [comment]
> It is for that reason that it was never translated. 

Also, I overlooked the `views` directories while extracting the translations. I was concentrating on the JS files and didn't realize there was language to be extracted in other places.

> It is just impossible to use the specific format for email strings because there are no php variables here. 

I spent some time last night thinking about how to approach these translations, and I encountered the same difficulty with the blade format: it tends to produce a sentence structure that is too inflexible.

Unfortunately your improved code won't avoid that issue, wirhwe. To accommodate localization into as many languages as possible, I suspect it will be necessary to move away from the full blade format. The best approach would probably end up looking something like what Toby has done for the confirmation emails in [SendConfirmationEmailController.php](https://github.com/flarum/core/blob/685d5f151793544a433d5f027f3dc87e80ec702f/src/Api/Controller/SendConfirmationEmailController.php). But I'm just guessing about that.

> At this point I cannot go further. The developers must first choose and tell me if they want to keep the blade.php format (above) or allow me to switch to standard php format.

I agree, one of them would be better able than I to suggest what your next step should be.

Thanks for your efforts on this, and for taking my comments into consideration.

**Comment by Averell7** [comment]
> I spent some time last night thinking about how to approach these translations, and I encountered the same difficulty with the blade format: it tends to produce a sentence structure that is too inflexible.

So we arrive to the same conclusion : The best option is switching to php format. In this case, it is no problem. For plain text format, the file is :

```
<?php 
$app_url = app()->url();
$data = [
            '{dest_username}' => $user->username,
            '{post_username' => $blueprint->post->user->username,
            '{post_title}' => $blueprint->post->discussion->title,
            '{url}' =>  $app_url . "/d/" . $blueprint->post->discussion_id . "/" . $blueprint->post->number,
            '{content}' => $blueprint->post->content            
        ];
echo app()->translator->trans('flarum-subscriptions.forum.email.body', $data);
?>
```
And the translation string is :

```
      body: |
        Hey {dest_username}!

        {post_username} made a post in a discussion you're following: {post_title}
        
        To view the new activity, check out the following link:
        {url}
        
        ---
        
        {content}
        
        ---
        
        You won't receive any more notifications about this discussion until you're up-to-date.
```

**Comment by dcsjapan** [comment]
One small change is needed: the key should be `flarum-subscriptions.email.new_post_notification.body`. Both `forum` and `email` are defined as second-level namespacing keys; only `email` is needed here.

The third-level key `new_post_notification` is also required, to distinguish this email from any other emails that might be added to the Subscriptions extension in the future.

@tobscure Eventually it will also be necessary to pass **two** gender variables to the translator: one each for `dest_username` and `post_username`. I just thought I'd mention that here, just in case it could affect how or where this code gets added.

**Comment by Averell7** [comment]
I also apologize because I had not ye studied the details about keys for translations. 
In case the standard php solution is accepted, there will be a question  : I will need two bodies, one for plain text et the other for html. If we stick to body: , then there will be : 
```
subscriptions.email.new_post_notification_text.body
subscriptions.email.new_post_notification_html.body
```
The other option would be to add a suffix to body : 
```
body_txt
body_html
```
which is much better IMHO. 
Multipart emails are a must, if we want to profit from the possibilities of html. A user which refuses html will not like to see a message full of html codes.

**Comment by dcsjapan** [comment]
I would have to defer to Toby's judgment, but I think we probably don't want more than one body text per email in the YAML files. We've been working hard to avoid such duplication of language resources.

It may be possible to get by with only the HTML version, but before we discuss that possibility any further, please allow me to ask a question and make sure I'm not misunderstanding:

Will the PHP code you posted above for the plain text format mail solve the HTML entities problem?

If it will, then perhaps it would be better to focus on closing this issue, and leave https://github.com/flarum/core/issues/241 for later. Trying to solve too many issues at once complicates the problem and makes it more difficult to implement quickly. (As you have seen, just adding the translations involves a few more complexities than one might expect.)

If the HTML entitles problem **can't** be solved without building HTML mail into the solution, then I may have an idea that will work.

**Comment by Averell7** [comment]
The htmlentities problem is solved in both codes posted above, pure PHP or blade.php. The final result is the same. 
So, you can assume that presently any type of mail can be generated : 

* plain text only
* html only
* html/plain text

All types will have a clean text (with additional formatting possible in html).

**Comment by Averell7** [comment]
I attach two screen capture : 
1. Plain text mail built with the above php file 
2. Html mail built with the blade version (I have not yet written the php version for html, but the result will be exactly the same)
![pure php-plain_text](https://cloud.githubusercontent.com/assets/858359/14404787/f996925a-fe7e-11e5-9a1e-c49f04987cfc.jpg)
![blade - html](https://cloud.githubusercontent.com/assets/858359/14404791/ffca6e9e-fe7e-11e5-8fdc-d7462b3538d9.jpg)

**Comment by Averell7** [comment]
Just for the fun : the same email in the beta5 version. 
![beta5](https://cloud.githubusercontent.com/assets/858359/14404922/a389e570-fe82-11e5-8600-380779d52769.jpg)

**Comment by Averell7** [comment]
@dcsjapan  I found the trick, it was so simple ! The body: string will be the html version, and the program will strip the html tags to have the plain/text version. 

As soon as you have decided about PHP or blade, I can finish the code.

**Comment by dcsjapan** [comment]
@Averell7 That's more or less what I had in mind. My only concern is to prevent the program from stripping HTML tags that should be left intact, e.g. any HTML tags inside a `[code]` block in the quoted post content.

The HTML version of the email can be added to the YAML file as described in the [Adding HTML Tags](http://flarum.org/docs/extend/internationalize/#html-tags) section of the i18n docs.

As we both concluded, the blade approach doesn't adapt well to translation; so I think it would probably be best to go with the PHP approach. Do you agree with this @tobscure ?

**Comment by Averell7** [comment]
> My only concern is to prevent the program from stripping HTML tags that should be left intact, e.g. any HTML tags inside a [code] block in the quoted post content.
A good regular expression can solve this.

**Comment by Averell7** [comment]
>My only concern is to prevent the program from stripping HTML tags that should be left intact, e.g. any HTML tags inside a [code] block in the quoted post content.

The version I updated on Github works fine 
https://github.com/flarum/flarum-ext-subscriptions/compare/master...Averell7:master

If @tobscure accepts it, we are done.

**Comment by luceos** [comment]
After having a lengthy discussion on Gitter with @dcsjapan , who patiently took the time to explain the translation issues involved here, I think it's best to do the following:
- do not drop blade formatting in the blade files; the [proposed pr](https://github.com/flarum/flarum-ext-subscriptions/compare/master...Averell7:master) uses only raw php in a blade file. Everything you are doing there can be done within blade. Dropping blade markup now might create future issues and can drop extensibility too.
- the reason for this issue is utf-8 support, best practice is to solve one issue per PR. Let's do that by using the [unescaped blade formatters Franz explained](https://github.com/flarum/core/issues/537#issuecomment-205555551). I recommend to work on full html support from issue flarum/issue-archive#426 and PR against that.
- the issue of utf-8 support has to be fixed for all emails, this also includes the mentions extension.

**Comment by Averell7** [comment]
> Everything you are doing there can be done within blade.

May be, but I don't know how and I cannot study blade for that, it must be done by someone who is familiar with this format. 

I gave above simple versions in blade format which cannot address the problem of translations, but fix the bug of this thread. Sorry if cannot help more, I have also my own programs to maintain. 

Remember to fix flarum/framework#920 It was fixed by my code, but if another takes the question afresh, the bug may arise again, so I opened again the issue. 

Remember also that perhaps something has to be fixed in flarum\vendor\flarum\core\js\lib\models\Post.js because contentPlain returns nothing. The function is in strings.js : 

```
export function getPlainContent(string) {
  const dom = $('<div/>').html(string.replace(/(<\/p>|<br>)/g, '$1 &nbsp;'));

  dom.find(getPlainContent.removeSelectors.join(',')).remove();

  return dom.text();
}

/**
 * An array of DOM selectors to remove when getting plain content.
 *
 * @type {Array}
 */
getPlainContent.removeSelectors = ['blockquote', 'script'];
```

That's all, guys. I hope you will find the right solution in blade.

**Comment by Averell7** [comment]
@dcsjapan , Thanks for the collaboration, I really appreciated working with you.

**Comment by dcsjapan** [comment]
@Averell7 Thank you ... and I'm sorry if I got things muddled. I thought trying to match the the code to that used for the confirmation emails was the right direction ... but @Luceos explained to me last night that the blade templating will be needed in the long run, to allow styling of the emails. That's an aspect that I hadn't considered.

**Comment by ExerciseBook** [comment]
`    # reset_password:
      # body: "\u0026\u006c\u0074\u003b\u0068\u0074\u006d\u006c\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0026\u006c\u0074\u003b\u006d\u0065\u0074\u0061\u0020\u0063\u0068\u0061\u0072\u0073\u0065\u0074\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0075\u0074\u0066\u002d\u0038\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0026\u006c\u0074\u003b\u0073\u0074\u0079\u006c\u0065\u0020\u0074\u0079\u0070\u0065\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0074\u0065\u0078\u0074\u002f\u0063\u0073\u0073\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u006d\u0065\u0064\u0069\u0061\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0061\u006c\u006c\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0023\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u005f\u0068\u0065\u0061\u0064\u0065\u0072\u0020\u007b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u006c\u0065\u0066\u0074\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u0009\u0009\u0070\u0061\u0064\u0064\u0069\u006e\u0067\u003a\u0020\u0032\u0030\u0070\u0078\u0020\u0032\u0030\u0070\u0078\u0020\u0030\u0070\u0078\u003b\u000d\u000a\u0009\u0009\u0062\u0061\u0063\u006b\u0067\u0072\u006f\u0075\u006e\u0064\u003a\u0020\u006e\u006f\u006e\u0065\u0020\u0072\u0065\u0070\u0065\u0061\u0074\u0020\u0073\u0063\u0072\u006f\u006c\u006c\u0020\u0030\u0025\u0020\u0030\u0025\u0020\u0023\u0066\u0066\u0066\u0066\u0066\u0066\u003b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u0074\u006f\u0070\u003a\u0020\u0035\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0044\u0036\u0033\u0030\u0033\u0030\u003b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u0072\u0069\u0067\u0068\u0074\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u0009\u0009\u006c\u0069\u006e\u0065\u002d\u0068\u0065\u0069\u0067\u0068\u0074\u003a\u0031\u0030\u0030\u0025\u003b\u000d\u000a\u0009\u0009\u007d\u000d\u000a\u0009\u0009\u0023\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u005f\u006d\u0061\u0069\u006e\u007b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u006c\u0065\u0066\u0074\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u0009\u0009\u0070\u0061\u0064\u0064\u0069\u006e\u0067\u003a\u0020\u0031\u0030\u0070\u0078\u0020\u0032\u0030\u0070\u0078\u003b\u000d\u000a\u0009\u0009\u0062\u0061\u0063\u006b\u0067\u0072\u006f\u0075\u006e\u0064\u003a\u0020\u006e\u006f\u006e\u0065\u0020\u0072\u0065\u0070\u0065\u0061\u0074\u0020\u0073\u0063\u0072\u006f\u006c\u006c\u0020\u0030\u0025\u0020\u0030\u0025\u0020\u0023\u0066\u0066\u0066\u0066\u0066\u0066\u003b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u0072\u0069\u0067\u0068\u0074\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u0009\u0009\u0074\u0065\u0078\u0074\u002d\u0061\u006c\u0069\u0067\u006e\u003a\u006c\u0065\u0066\u0074\u003b\u000d\u000a\u0009\u0009\u0074\u0065\u0078\u0074\u002d\u0069\u006e\u0064\u0065\u006e\u0074\u003a\u0032\u0065\u006d\u003b\u000d\u000a\u0009\u0009\u007d\u000d\u000a\u0009\u0009\u0023\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u005f\u0065\u006e\u0064\u0069\u006e\u0067\u007b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u006c\u0065\u0066\u0074\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u0009\u0009\u0070\u0061\u0064\u0064\u0069\u006e\u0067\u003a\u0020\u0031\u0030\u0070\u0078\u0020\u0032\u0030\u0070\u0078\u003b\u000d\u000a\u0009\u0009\u0062\u0061\u0063\u006b\u0067\u0072\u006f\u0075\u006e\u0064\u003a\u0020\u006e\u006f\u006e\u0065\u0020\u0072\u0065\u0070\u0065\u0061\u0074\u0020\u0073\u0063\u0072\u006f\u006c\u006c\u0020\u0030\u0025\u0020\u0030\u0025\u0020\u0023\u0066\u0066\u0066\u0066\u0066\u0066\u003b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u0072\u0069\u0067\u0068\u0074\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u0009\u0009\u0074\u0065\u0078\u0074\u002d\u0061\u006c\u0069\u0067\u006e\u003a\u0072\u0069\u0067\u0068\u0074\u003b\u000d\u000a\u0009\u0009\u0074\u0065\u0078\u0074\u002d\u0069\u006e\u0064\u0065\u006e\u0074\u003a\u0032\u0065\u006d\u003b\u000d\u000a\u0009\u0009\u007d\u000d\u000a\u0009\u0009\u0023\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u005f\u0066\u006f\u006f\u0074\u0065\u0072\u007b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u0062\u006f\u0074\u0074\u006f\u006d\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u006c\u0065\u0066\u0074\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u0009\u0009\u0070\u0061\u0064\u0064\u0069\u006e\u0067\u003a\u0020\u0030\u0070\u0078\u0020\u0032\u0030\u0070\u0078\u0020\u0032\u0030\u0070\u0078\u003b\u000d\u000a\u0009\u0009\u0062\u0061\u0063\u006b\u0067\u0072\u006f\u0075\u006e\u0064\u003a\u0020\u006e\u006f\u006e\u0065\u0020\u0072\u0065\u0070\u0065\u0061\u0074\u0020\u0073\u0063\u0072\u006f\u006c\u006c\u0020\u0030\u0025\u0020\u0030\u0025\u0020\u0023\u0066\u0066\u0066\u0066\u0066\u0066\u003b\u000d\u000a\u0009\u0009\u0062\u006f\u0072\u0064\u0065\u0072\u002d\u0072\u0069\u0067\u0068\u0074\u003a\u0020\u0031\u0070\u0078\u0020\u0073\u006f\u006c\u0069\u0064\u0020\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u000d\u000a\u000d\u000a\u0009\u0026\u006c\u0074\u003b\u002f\u0073\u0074\u0079\u006c\u0065\u0026\u0067\u0074\u003b\u000d\u000a\u000d\u000a\u0009\u0026\u006c\u0074\u003b\u0062\u006f\u0064\u0079\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0061\u0062\u006c\u0065\u0020\u0077\u0069\u0064\u0074\u0068\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0036\u0034\u0038\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u0061\u006c\u0069\u0067\u006e\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u0065\u006e\u0074\u0065\u0072\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u0073\u0074\u0079\u006c\u0065\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u006d\u0061\u0072\u0067\u0069\u006e\u003a\u0020\u0032\u0035\u0070\u0078\u0020\u0061\u0075\u0074\u006f\u003b\u0020\u0066\u006f\u006e\u0074\u002d\u0066\u0061\u006d\u0069\u006c\u0079\u003a\u0020\u004d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u0020\u0059\u0061\u0048\u0065\u0069\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u0062\u006f\u0072\u0064\u0065\u0072\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0030\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u0063\u0065\u006c\u006c\u0073\u0070\u0061\u0063\u0069\u006e\u0067\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0030\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u0063\u0065\u006c\u006c\u0070\u0061\u0064\u0064\u0069\u006e\u0067\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0030\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0062\u006f\u0064\u0079\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0064\u0020\u0073\u0074\u0079\u006c\u0065\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u006f\u006c\u006f\u0072\u003a\u0023\u0044\u0036\u0033\u0030\u0033\u0030\u003b\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u0026\u006c\u0074\u003b\u0068\u0031\u0020\u0073\u0074\u0079\u006c\u0065\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u006d\u0061\u0072\u0067\u0069\u006e\u002d\u0062\u006f\u0074\u0074\u006f\u006d\u003a\u0031\u0030\u0070\u0078\u003b\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u007b\u0066\u006f\u0072\u0075\u006d\u007d\u0026\u006e\u0062\u0073\u0070\u003b\u0026\u006c\u0074\u003b\u0066\u006f\u006e\u0074\u0020\u0073\u0069\u007a\u0065\u003d\u0033\u0026\u0067\u0074\u003b\u91cd\u7f6e\u5bc6\u7801\u0026\u006c\u0074\u003b\u002f\u0066\u006f\u006e\u0074\u0026\u0067\u0074\u003b\u0026\u006c\u0074\u003b\u002f\u0068\u0031\u0026\u0067\u0074\u003b\u0026\u006c\u0074\u003b\u002f\u0074\u0064\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0064\u0020\u0069\u0064\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u005f\u0068\u0065\u0061\u0064\u0065\u0072\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0070\u0026\u0067\u0074\u003b\u8fd9\u4f4d\u65b0\u670b\u53cb\uff1a\u0026\u006c\u0074\u003b\u002f\u0070\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0064\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0064\u0020\u0069\u0064\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u005f\u006d\u0061\u0069\u006e\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0070\u0026\u0067\u0074\u003b\u007b\u0075\u0073\u0065\u0072\u006e\u0061\u006d\u0065\u007d\u0020\u60a8\u597d\uff01\u0026\u006c\u0074\u003b\u002f\u0070\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0070\u0026\u0067\u0074\u003b\u6709\u4eba\u60f3\u91cd\u7f6e\u60a8\u5728\u0026\u006e\u0062\u0073\u0070\u003b\u0026\u006c\u0074\u003b\u0066\u006f\u006e\u0074\u0020\u0063\u006f\u006c\u006f\u0072\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0023\u0038\u0030\u0030\u0030\u0038\u0030\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u007b\u0066\u006f\u0072\u0075\u006d\u007d\u0026\u006c\u0074\u003b\u002f\u0066\u006f\u006e\u0074\u0026\u0067\u0074\u003b\u0026\u006e\u0062\u0073\u0070\u003b\u7684\u5bc6\u7801\u3002\u0026\u006c\u0074\u003b\u002f\u0070\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0070\u0026\u0067\u0074\u003b\u82e5\u8fd9\u662f\u60a8\u7684\u64cd\u4f5c\uff0c\u7686\u5927\u6b22\u559c\u3002\u8bf7\u0026\u006c\u0074\u003b\u0061\u0020\u0068\u0072\u0065\u0066\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u007b\u0075\u0072\u006c\u007d\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u0074\u0061\u0072\u0067\u0065\u0074\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u005f\u0062\u006c\u0061\u006e\u006b\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u0073\u0074\u0079\u006c\u0065\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0066\u006f\u006e\u0074\u002d\u0077\u0065\u0069\u0067\u0068\u0074\u003a\u0062\u006f\u006c\u0064\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u70b9\u51fb\u94fe\u63a5\u0026\u006c\u0074\u003b\u002f\u0061\u0026\u0067\u0074\u003b\u4fee\u6539\u5bc6\u7801\u3002\u0026\u006c\u0074\u003b\u002f\u0070\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0070\u0026\u0067\u0074\u003b\u82e5\u8fd9\u4e0d\u662f\u60a8\u7684\u64cd\u4f5c\uff0c\u5341\u5206\u62b1\u6b49\u6253\u6270\u60a8\u4e86\uff0c\u8bf7\u60a8\u65e0\u89c6\u672c\u90ae\u4ef6\u5373\u53ef\uff0c\u6211\u4eec\u4e5f\u4e0d\u4f1a\u53d7\u7406\u672c\u6b21\u64cd\u4f5c\u3002\u0026\u006c\u0074\u003b\u002f\u0070\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0064\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0064\u0020\u0069\u0064\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u005f\u0065\u006e\u0064\u0069\u006e\u0067\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0070\u0026\u0067\u0074\u003b\u007b\u0066\u006f\u0072\u0075\u006d\u007d\u0020\u7684\u670d\u52a1\u5668\u656c\u4e0a\u0026\u006c\u0074\u003b\u002f\u0070\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0064\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0074\u0064\u0020\u0069\u0064\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u005f\u0066\u006f\u006f\u0074\u0065\u0072\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0068\u0072\u0020\u0073\u0074\u0079\u006c\u0065\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u006f\u006c\u006f\u0072\u003a\u0023\u0063\u0063\u0063\u003b\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0070\u0020\u0073\u0074\u0079\u006c\u0065\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u006f\u006c\u006f\u0072\u003a\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u0066\u006f\u006e\u0074\u002d\u0073\u0069\u007a\u0065\u003a\u0039\u0070\u0074\u003b\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u5982\u679c\u4e0a\u9762\u7684\u94fe\u63a5\u65e0\u6cd5\u88ab\u8bc6\u522b\uff0c\u53ef\u4ee5\u4f7f\u7528\u8fd9\u4e00\u4e2a\u94fe\u63a5\u5e76\u5c06\u5176\u590d\u5236\u5230\u6d4f\u89c8\u5668\u5730\u5740\u680f\u5185\uff1a\u0026\u006e\u0062\u0073\u0070\u003b\u007b\u0075\u0072\u006c\u007d\u0026\u006c\u0074\u003b\u002f\u0061\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u0070\u0020\u0073\u0074\u0079\u006c\u0065\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0063\u006f\u006c\u006f\u0072\u003a\u0023\u0046\u0032\u0036\u0035\u0036\u0035\u003b\u0066\u006f\u006e\u0074\u002d\u0073\u0069\u007a\u0065\u003a\u0039\u0070\u0074\u003b\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u60f3\u4e86\u89e3\u66f4\u591a\u4fe1\u606f\uff0c\u8bf7\u8bbf\u95ee\u0026\u006e\u0062\u0073\u0070\u003b\u0026\u006c\u0074\u003b\u0061\u0020\u0068\u0072\u0065\u0066\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u002e\u0070\u0061\u0072\u0061\u002e\u0070\u0061\u0072\u0074\u0079\u0026\u0071\u0075\u006f\u0074\u003b\u0020\u0074\u0061\u0072\u0067\u0065\u0074\u003d\u0026\u0071\u0075\u006f\u0074\u003b\u005f\u0062\u006c\u0061\u006e\u006b\u0026\u0071\u0075\u006f\u0074\u003b\u0026\u0067\u0074\u003b\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u002e\u0070\u0061\u0072\u0061\u002e\u0070\u0061\u0072\u0074\u0079\u0026\u006c\u0074\u003b\u002f\u0061\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0070\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0064\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0072\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0062\u006f\u0064\u0079\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0009\u0026\u006c\u0074\u003b\u002f\u0074\u0061\u0062\u006c\u0065\u0026\u0067\u0074\u003b\u000d\u000a\u0009\u0026\u006c\u0074\u003b\u002f\u0062\u006f\u0064\u0079\u0026\u0067\u0074\u003b\u000d\u000a\u0026\u006c\u0074\u003b\u002f\u0068\u0074\u006d\u006c\u0026\u0067\u0074\u003b\u000d\u000a"
      # subject: 密码重置`

![1](https://cloud.githubusercontent.com/assets/6327311/22088400/b7f5cc32-de1e-11e6-9f9e-2e58f7310fb3.png)

![2](https://cloud.githubusercontent.com/assets/6327311/22088412/d5f7caf0-de1e-11e6-9651-01ab17bf2e46.png)


HTML is doesn't work in Email ?

**Comment by franzliedke** [comment]
Can anybody still reproduce this issue with one of the example posts such as this one?

> Le problème de la ligne téléphonique a été réparé
Le problème de la ligne téléphonique est réparé.

This works fine for me in beta-8.1. No HTML entities.

@JoshyPHP Did TextFormatter stop turning UTF-8 characters into HTML entities at some point during the last two years?

**Comment by JoshyPHP** [comment]
> Did TextFormatter stop turning UTF-8 characters into HTML entities at some point during the last two years?

No, nothing's changed.

**Comment by franzliedke** [comment]
I can't quite put my finger on why, but the problem seems to be fixed. Might have been because of a Laravel upgrade then.

**Comment by matteocontrini** [comment]
@franzliedke I'm pretty sure it was fixed through https://github.com/flarum/subscriptions/commit/91128ceea0753efb1aac880782b95c67793b56cf and https://github.com/flarum/mentions/commit/5f8ef04271a5a35fa390286f976fa7e31f389a5f
