### ISSUE TITLE
Failures on PHP 7

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#685]
***1 Upvote*** We have a [forum thread](https://discuss.flarum.org/d/1390-migrating-from-php-5-6-x-to-php-7-0-x) with information about failures on PHP 7.

We'll have to test Flarum on PHP 7 and see if we can reproduce the issues and trace them to their origins.

In addition, we need to go through the migration guide to see whether anything more subtle needs changing. (Exceptions/Throwables are such a topic.)

**Comment by Luceos** [comment]
+1

**Comment by xf-liam** [comment]
Hi,

I use PHP7 on my installs, so I wanted to get it working. It's been a headache, and all I've done is work around the issue.

The issue is that, for some reason, the json_encode call in the JsonResponse::jsonEncode method for the api call to get the user document is throwing a parse error.

This is strange, because if you add the JSON_PARTIAL_OUTPUT_ON_ERROR flag, it works fine (I checked, adding that flag gives the same output as PHP 5.6, bar the json syntax error).

I have a right mind to say this is a PHP bug... But I can't figure out a minimal code sample to reproduce, so it may not be a PHP bug...

Either way, changing the method to this lets me run it on PHP7 (for now at least):

    private function jsonEncode($data, $encodingOptions)
    {
        if (is_resource($data)) {
            throw new InvalidArgumentException('Cannot JSON encode resources');
        }

        // Clear json_last_error()
        json_encode(null);

        $json = json_encode($data, $encodingOptions | JSON_PARTIAL_OUTPUT_ON_ERROR);

        json_encode(null);

        if (JSON_ERROR_NONE !== json_last_error()) {
            throw new InvalidArgumentException(sprintf(
                'Unable to encode data to JSON in %s: %s',
                __CLASS__,
                json_last_error_msg()
            ));
        }

        return $json;
    }

**Comment by franzliedke** [comment]
Thanks for your detailed investigation, @xf-liam. I will try to see whether I find any additional reports about behavior like this on PHP7.

Can you dump the payload that is being encoded when the error occurs, please?

**Comment by liamwli** [comment]
Unfortunately, no. It causes the memory limit to be exhausted... (It tries to allocate over 500MB after using the limit of 128MB).

I've upped my limit, but now it's timing out. It's an exceptionally large load...

**Comment by Cleanse** [comment]
I am getting the following, OSX + PHP 7.0.2:

```
( ! ) Notice: Undefined property: stdClass::$data in /install-dir/flarum/vendor/flarum/core/src/Http/Controller/ClientView.php on line 326
Call Stack
#	Time	Memory	Function	Location
1	0.0062	364320	{main}( )	.../index.php:0
2	0.0436	954920	Flarum\Http\AbstractServer->listen( )	.../index.php:16
3	0.2209	6089408	Zend\Diactoros\Server->listen( )	.../AbstractServer.php:33
4	0.2209	6105872	Zend\Stratigility\MiddlewarePipe->__invoke( )	.../Server.php:166
5	0.2224	6217600	Zend\Stratigility\Next->__invoke( )	.../MiddlewarePipe.php:75
6	0.2225	6217984	Zend\Stratigility\Dispatch->__invoke( )	.../Next.php:113
7	0.2225	6217992	call_user_func:{/install-dir/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php:81} ( )	.../Dispatch.php:81
8	0.2225	6217992	Flarum\Http\Middleware\AuthenticateWithCookie->__invoke( )	.../Dispatch.php:81
9	0.2351	6798872	Zend\Stratigility\Next->__invoke( )	.../AuthenticateWithCookie.php:42
10	0.2352	6799216	Zend\Stratigility\Dispatch->__invoke( )	.../Next.php:113
11	0.2352	6799224	
```

**Comment by liamwli** [comment]
That's directly related to the issue I posted above. The json is an error, and doesn't have a data property.

**Comment by Cleanse** [comment]
@liamwli Your fix to the zend package didnt fix anything for me.

**Comment by christophermancini** [comment]
Seeing this issue as well on PHP 7.0.2 compiled on Amazon Linux.

**Comment by sijad** [comment]
sijad/core@291dff7bfb7a2ac2061f864bba383caaa249b12b fixes the problem with php 7 in client view, I'm not sure if is the right way to fix this though but it's working

**Comment by webeindustry** [comment]
I'm confirming the above issue was fixed applying https://github.com/sijad/core/commit/291dff7bfb7a2ac2061f864bba383caaa249b12b

On Ubuntu 16.04 beta1, php7.0

**Comment by sijad** [comment]
@franzliedke if you're busy, can I spend more time on this?

**Comment by franzliedke** [comment]
Sure. Your solution seems to work, but I'd like for someone (either you or me) to find out why this is necessary. It should work without it. ;)

**Comment by sijad** [comment]
after spending much time on this, I guess it was a php bug, I've updated to php 7.0.4 and problem seems solved, can you confirm this @franzliedke?

**Comment by franzliedke** [comment]
Ah, too bad. ;)

I will check again tonight, but I saw nothing of interest in the [PHP 7 changelog](http://www.php.net/ChangeLog-7.php). There are some interesting bugs that were fixed in v7.0.0, but apparently that did not fix our problem...

**Comment by franzliedke** [comment]
Okay, I have given up on this one.

Thanks for all your efforts, @sijad. There must be some internal problem going on. I can encode the JSON-API document from Toby's library when I pass in the result of its `toArray()` method, but when passing in the object itself, it will not work. Go figure.

For documentation, here's a 3v4l script that was supposed to document this issue, but it worked there: https://3v4l.org/6ceWk

I've sent an email to @bukka, the maintainer of PHP's new JSON(D) extension. Maybe he has some input...

I will now use the workaround suggested by @sijad. Thanks a lot!

**Comment by Luceos** [comment]
@franzliedke it might be wise to create a related issue marked technical debt (or clean up) so we can re-evaluate this in the future and perhaps clean up the code on future builds.
