### ISSUE TITLE
[Markdown] backticks ``` and quotes

### ISSUE THREAD

**Issue by kulga** [flarum/core#771]
Backticks -> ```

don't seem to stop quotes with > in [flarum](https://discuss.flarum.org/d/1998-test)

```
# header
```

```
> test quote with >
# header
```

**Comment by JoshyPHP** [comment]
Should be fixed by https://github.com/s9e/TextFormatter/commit/9f2b080f01f74b4943d12d5b246dc0949673cdfa

@kulga You can try the latest version on [this page](http://s9e.github.io/TextFormatter/fatdown.html), see if it works better for you.

**Comment by Luceos** [comment]
@tobscure could you add a tag here called "3rd party" or "extension"?

Todo: dependency update.

**Comment by franzliedke** [comment]
The dependency version constraint has already been updated.

**Comment by datitisev** [comment]
Has this supposedly been fixed on Flarum or TextFormatter
As far as I can tell, it still doesn't work on either of those :/

**Comment by franzliedke** [comment]
If I understand this correctly, [it works now](https://discuss.flarum.org/d/1998-test/7).

We definitely upgraded to the newest TextFormatter release.

**Comment by datitisev** [comment]
How did it work before, and how is it supposed to work?
I'm confused.
Is the point to be able to have quotes inside backticks or not?

**Comment by kulga** [comment]
@datitisev [Before](https://discuss.flarum.org/d/1998-test) [After](https://discuss.flarum.org/d/1998-test/7)
